FROM python@sha256:baf89808ec37adeaab83cec287adb4a2afa4a11c1d51e961c7ec737877e61af6
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
COPY requirements.bridge.txt .
COPY app ./app
RUN pip install --no-cache-dir -r requirements.bridge.txt
COPY alembic ./alembic
COPY alembic.ini .
CMD ["uvicorn", "app.bridge_app:app", "--host", "0.0.0.0", "--port", "8000", "--no-access-log"]
