"""use varchar enums

Revision ID: 1c4ac6a7d61c
Revises: f45feef62312
Create Date: 2026-07-16 10:08:02.266471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c4ac6a7d61c'
down_revision = 'f45feef62312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'category',
               existing_type=postgresql.ENUM('core', 'natural', 'cultural', 'entertainment', 'shopping', 'local_specialty', 'personal_preference', 'niche', 'food', 'lodging', 'transport', name='candidatecategory'),
               type_=sa.Enum('core', 'natural', 'cultural', 'entertainment', 'shopping', 'local_specialty', 'personal_preference', 'niche', 'food', 'lodging', 'transport', name='candidatecategory', native_enum=False),
               existing_nullable=False)
    op.alter_column('candidates', 'tier',
               existing_type=postgresql.ENUM('must_go', 'strongly_recommended', 'optional', 'resource_pool', 'discarded', name='candidatetier'),
               type_=sa.Enum('must_go', 'strongly_recommended', 'optional', 'resource_pool', 'discarded', name='candidatetier', native_enum=False),
               existing_nullable=False)
    op.alter_column('collection_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'),
               type_=sa.Enum('pending', 'running', 'generating', 'partial', 'success', 'failed', name='collectionstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('draft', 'collecting', 'generating', 'ready', 'error', name='projectstatus'),
               type_=sa.Enum('draft', 'collecting', 'generating', 'ready', 'error', name='projectstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'),
               type_=sa.Enum('pending', 'running', 'generating', 'partial', 'success', 'failed', name='collectionstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('votes', 'vote_type',
               existing_type=postgresql.ENUM('like', 'dislike', 'neutral', name='votetype'),
               type_=sa.Enum('like', 'dislike', 'neutral', name='votetype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'vote_type',
               existing_type=sa.Enum('like', 'dislike', 'neutral', name='votetype', native_enum=False),
               type_=postgresql.ENUM('like', 'dislike', 'neutral', name='votetype'),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('pending', 'running', 'generating', 'partial', 'success', 'failed', name='collectionstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('draft', 'collecting', 'generating', 'ready', 'error', name='projectstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'collecting', 'generating', 'ready', 'error', name='projectstatus'),
               existing_nullable=False)
    op.alter_column('collection_runs', 'status',
               existing_type=sa.Enum('pending', 'running', 'generating', 'partial', 'success', 'failed', name='collectionstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'),
               existing_nullable=False)
    op.alter_column('candidates', 'tier',
               existing_type=sa.Enum('must_go', 'strongly_recommended', 'optional', 'resource_pool', 'discarded', name='candidatetier', native_enum=False),
               type_=postgresql.ENUM('must_go', 'strongly_recommended', 'optional', 'resource_pool', 'discarded', name='candidatetier'),
               existing_nullable=False)
    op.alter_column('candidates', 'category',
               existing_type=sa.Enum('core', 'natural', 'cultural', 'entertainment', 'shopping', 'local_specialty', 'personal_preference', 'niche', 'food', 'lodging', 'transport', name='candidatecategory', native_enum=False),
               type_=postgresql.ENUM('core', 'natural', 'cultural', 'entertainment', 'shopping', 'local_specialty', 'personal_preference', 'niche', 'food', 'lodging', 'transport', name='candidatecategory'),
               existing_nullable=False)
    # ### end Alembic commands ###
