"""add creator_token, candidate review fields, vote dedupe constraint

Revision ID: b1270b2f0ef9
Revises: 1c4ac6a7d61c
Create Date: 2026-07-17 20:01:34.610404

Captures schema drift that previously existed only via create_all:
- projects.creator_token (NOT NULL; safe on empty/fresh databases —
  existing dev databases were created with this column already)
- candidates.pros / cons / review_snippets (review_insights output)
- votes uq_vote_candidate_session unique constraint
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1270b2f0ef9'
down_revision = '1c4ac6a7d61c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('pros', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('cons', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('review_snippets', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('creator_token', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_projects_creator_token'), 'projects', ['creator_token'], unique=True)
    op.create_unique_constraint('uq_vote_candidate_session', 'votes', ['candidate_id', 'session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vote_candidate_session', 'votes', type_='unique')
    op.drop_index(op.f('ix_projects_creator_token'), table_name='projects')
    op.drop_column('projects', 'creator_token')
    op.drop_column('candidates', 'review_snippets')
    op.drop_column('candidates', 'cons')
    op.drop_column('candidates', 'pros')
    # ### end Alembic commands ###
