"""initial schema

Revision ID: f45feef62312
Revises: 
Create Date: 2026-07-16 09:49:20.953083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45feef62312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('travel_time', sa.String(length=100), nullable=True),
    sa.Column('departure', sa.String(length=255), nullable=False),
    sa.Column('traveler_structure', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('budget_level', sa.String(length=50), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'collecting', 'generating', 'ready', 'error', name='projectstatus'), nullable=False),
    sa.Column('votes_revealed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_token'), 'projects', ['token'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('core', 'natural', 'cultural', 'entertainment', 'shopping', 'local_specialty', 'personal_preference', 'niche', 'food', 'lodging', 'transport', name='candidatecategory'), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Enum('must_go', 'strongly_recommended', 'optional', 'resource_pool', 'discarded', name='candidatetier'), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('positive_summary', sa.Text(), nullable=True),
    sa.Column('negative_summary', sa.Text(), nullable=True),
    sa.Column('pitfalls_summary', sa.Text(), nullable=True),
    sa.Column('chinese_focus_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_area'), 'candidates', ['area'], unique=False)
    op.create_index(op.f('ix_candidates_category'), 'candidates', ['category'], unique=False)
    op.create_index(op.f('ix_candidates_external_id'), 'candidates', ['external_id'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_project_id'), 'candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_candidates_tier'), 'candidates', ['tier'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'), nullable=False),
    sa.Column('source_statuses', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_id'), 'collection_runs', ['id'], unique=False)
    op.create_index(op.f('ix_collection_runs_project_id'), 'collection_runs', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'partial', 'success', 'failed', name='collectionstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_candidate_id'), 'images', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('vote_type', sa.Enum('like', 'dislike', 'neutral', name='votetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_session_id'), 'votes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_session_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_candidate_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_collection_runs_project_id'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_candidates_tier'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_project_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_external_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_category'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_area'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_projects_token'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
